config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create,:show] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future
  before_validation :generate_code

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, "deve ser futura")
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :sku, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def description
    "#{name} - #{email}"
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :area, :address, :cep, :description, presence: true
  validates :code, uniqueness: true

  def full_description
    "#{code} - #{name}"
  end
end

app/controllers/api/v1/warehouses_controller.rb
class Api::V1::WarehousesController <ActionController::API

  def show
    warehouse = Warehouse.find(params[:id])
    render status: 200, json: warehouse.as_json(except: ["created_at", "area", "update_at"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def  create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.new(order_params)
    @order.user = current_user
    @order.save
    redirect_to @order, notice: 'Pedido registrado com sucesso'
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @suppliers = Supplier.all
    product_model_params = params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
    redirect_to @product_model,  notice: 'Modelo de produto cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível cadastrar modelo de produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController


  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(suppliers_params)
    if @supplier.save
    redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso!'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'new'
      end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    if @supplier.update(suppliers_params)
      redirect_to supplier_path, notice: 'Fornecedor editado com sucesso'
    else
      flash.now[:notice] = 'Não foi possível editar o fornecedor'
      render 'edit'
    end
  end

  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.delete
    redirect_to suppliers_path, notice: 'Fornecedor removido com sucesso'
  end


  private

  def suppliers_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController

  before_action :set_warehouse, only: [:edit, :update, :show, :destroy]

  def show
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
    redirect_to root_path, notice: 'Galpão cadastrado com sucesso'
    else
    flash.now[:notice] = 'Galpão não cadastrado'
    render 'new'
    end
  end

  def edit
  end

  def update
    if @warehouse.update(warehouse_params)
    redirect_to warehouse_path, notice: 'Galpão editado com sucesso!'
    else
      flash.now[:notice] = 'Não foi possível editar o galpão'
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :description, :address, :cep, :area)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id= 'warehouses'>

  <p><%=I18n.localize(Date.today)%></p>
<h2>Galpões</h2>
<div>
  <%= link_to  "Cadastrar Galpão", new_warehouse_path%>
</div>
<%@warehouses.each do |warehouse|%>
<div>
  <h3><%=link_to warehouse.name, warehouse_path(warehouse.id) %></h3>
  <dl>
    <dt>Código:</dt>
    <dd><%=warehouse.code%></dd>
    <dt>Cidade:</dt>
    <dd><%=warehouse.city%></dd>
    <dt>Área:</dt>
    <dd><%=warehouse.area%> m²</dd>
  </dl>
<% end %>
</div>
<% if @warehouses.empty?  %>
  <p>Não existem galpões cadastrados</p>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to  root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav>
        <%= link_to  "Fornecedores", suppliers_path %> | 
        <%= link_to  "Modelos de Produtos", product_models_path %> | 
        <%= link_to  "Registrar Pedido", new_order_path %> |
        <%if user_signed_in?%>
          <%=form_with url: search_orders_path, method: :get do |f| %>
          <%= f.label :query, 'Buscar Pedido' %>
          <%= f.text_field :query %>
          <%= f.submit 'Buscar' %>
          <% end %>
          <%=current_user.description%>
          <%= button_to  "Sair", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to  "Entrar", new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <main>
      <div>
        <p><%=notice%></p>
        <p><%=alert%></p>
      </div>
    <%= yield %>
    </main>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Registrar Pedido</h1>

<%=form_with(model: @order) do |f|%>
  <div>
    <%= f.label :warehouse_id%>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>
  <div>
    <%= f.label :supplier_id%>
    <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date%>
    <%= f.text_field :estimated_delivery_date %>
  </div>
  <%= f.submit 'Gravar' %>
<% end %>

app/views/orders/show.html.erb
<h2><%= Order.model_name.human%> <%= @order.code %></h2>

<dl>
  <dt><%= Order.human_attribute_name(:warehouse_id)%>:</dt>
  <dd><%=@order.warehouse.full_description%></dd>
  <dt><%= Order.human_attribute_name(:supplier_id)%>:</dt>
  <dd><%=@order.supplier.corporate_name%></dd>
  <dt><%= Order.human_attribute_name(:estimated_delivery_date)%>:</dt>
  <dd><%=I18n.localize(@order.estimated_delivery_date)%></dd>
  <dt><%= Order.human_attribute_name(:user_id)%>:</dt>
  <dd><%=@order.user.name%> | <%=@order.user.email%> </dd>
</dl>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>
<%=link_to  "Cadastrar Novo",  new_product_model_path%>

<% if @product_models.any? %>

  <%@product_models.each do |product|%>
    <div>
      <h2><%=product.name%></h2>
      <dl>
        <dt>SKU</dt>
        <dd><%=product.sku%></dd>
        <dt>Fornecedor</dt>
        <dd><%=product.supplier.brand_name%></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p> Não existe nenhum produto cadastrado </p>  
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produtos</h1>

<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>
  <div>
    <%= f.label :weight%>
    <%= f.number_field :weight%>
  </div>
  <div>
    <%= f.label :width%>
    <%= f.number_field :width%>
  </div>
  <div>
    <%= f.label :height%>
    <%= f.number_field :height%>
  </div>
  <div>
    <%= f.label :depth%>
    <%= f.number_field :depth%>
  </div>
  <div>
    <%= f.label :sku%>
    <%= f.text_field :sku%>
  </div>
  <div>
    <%= f.label :supplier_id%>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name%>
  </div>
  <%= f.submit 'Enviar'%>
<% end %>

app/views/product_models/show.html.erb
<h1><%=@product_model.name%></h1>

<dl>
  <dt>Fornecedor:</dt>
  <dd><%=@product_model.supplier.brand_name%></dd>
  <dt>SKU:</dt>
  <dd><%=@product_model.sku%></dd>
  <dt>Dimensão:</dt>
  <dd><%=@product_model.height%>cm x <%=@product_model.width%>cm x <%=@product_model.depth%>cm</dd>
  <dt>Peso:</dt>
  <dd><%=@product_model.weight%>g</dd>
</dl>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= form_with(model: @supplier) do |f| %>
<div>
<%= f.label :corporate_name%>
<%= f.text_field :corporate_name%>
</div>
<div>
<%= f.label :brand_name%>
<%= f.text_field :brand_name%>

<div>
<%= f.label :registration_number%>
<%= f.text_field :registration_number%>
</div>
<div>
<%= f.label :full_address%>
<%= f.text_field :full_address%>
</div>
<div>
<%= f.label :city%>
<%= f.text_field :city%>
</div>
<div>
<%= f.label :state%>
<%= f.text_field :state%>
</div>
<div>
<%= f.label :email%>
<%= f.email_field :email%>
</div>
<%= f.submit 'Enviar' %>
<% end %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>
<div><%= link_to  "Novo Fornecedor", new_supplier_path %></div>
<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <%@suppliers.each do |supplier|%>
      <tr>
        <td><%=link_to supplier.brand_name, supplier%></td>
        <td><%=supplier.city%> - <%=supplier.state%></td>
      </tr>
      <% end %>
  </tbody>
  </table>
  <% else %>
  <p>Não existem fornecedores cadastrados</p>
<% end %>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>


<%= form_with(model: @supplier) do |f| %>
<div>
<%= f.label :corporate_name%>
<%= f.text_field :corporate_name%>
</div>
<div>
<%= f.label :brand_name%>
<%= f.text_field :brand_name%>

<div>
<%= f.label :registration_number%>
<%= f.text_field :registration_number%>
</div>
<div>
<%= f.label :full_address%>
<%= f.text_field :full_address%>
</div>
<div>
<%= f.label :city%>
<%= f.text_field :city%>
</div>
<div>
<%= f.label :state%>
<%= f.text_field :state%>
</div>
<div>
<%= f.label :email%>
<%= f.email_field :email%>
</div>
<%= f.submit 'Enviar' %>
<% end %>

app/views/suppliers/show.html.erb
<h1><%= @supplier.corporate_name%></h1>
<div>
  <dl>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @supplier.brand_name%></dd>
    <dt><strong>Registro:</strong></dt>
    <dd><%= @supplier.registration_number%></dd>
    <dt><strong>Endereço:</strong></dt>
    <dd><%= @supplier.full_address%></dd>
    <dt><strong>Cidade:</strong></dt>
    <dd><%= @supplier.city%> m²</dd>
    <dt><strong>Estado:</strong></dt>
    <dd><%= @supplier.state%></dd>
    <dt><strong>Email:</strong></dt>
    <dd><%= @supplier.email%></dd>
  </dl>
</div>

<div>
  <%= link_to  "Editar", edit_supplier_path %>
  <%= button_to  "Remover", supplier_path, method: :delete %>
</div>
<div>
  <%= link_to  "Voltar", suppliers_path %>
</div>

app/views/warehouses/_form.html.erb
<%= form_with(model: @warehouse) do |f| %>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :code%>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :city%>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :address%>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :cep%>
    <%= f.text_field :cep %>
  </div>
  <div>
    <%= f.label :area%>
    <%= f.number_field :area %>
  </div>
  <div>
    <%= f.label :description%>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit 'Enviar'%>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h2>Editar Galpão</h2>

<%= render  "form" %>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>

<%if @warehouse.errors.any?%>
  <p>Verifique os erros abaixo: </p>
  <ul>
    <%@warehouse.errors.full_messages.each do |msg|%>
      <li><%=msg%></li>
    <% end %>
  </ul>
<% end %>

<%= render  "form" %>

app/views/warehouses/show.html.erb
<h1>Galpão <%= @warehouse.code%></h1>
<h2><%=@warehouse.description%></h2>
<div>
  <dl>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @warehouse.name%></dd>
    <dt><strong>Cidade:</strong></dt>
    <dd><%= @warehouse.city%></dd>
    <dt><strong>Área:</strong></dt>
    <dd><%= @warehouse.area%> m²</dd>
    <dt><strong>Endereço:</strong></dt>
    <dd><%= @warehouse.address%></dd>
    <dt><strong>CEP:</strong></dt>
    <dd><%= @warehouse.cep%></dd>
  </dl>
</div>

<%= link_to  "Voltar", root_path%>
<%= link_to  "Editar", edit_warehouse_path%>
<%= button_to  "Remover", warehouse_path, method: :delete%>